from models.DAO import DAO
from utils.exception import ValidationError

def add_staff(username, email, password, role_id, first_name = '', last_name = '', gender = '', phone = ''):
    pass
